"""Added date columns.

Revision ID: f07b511c58dc
Revises:
Create Date: 2026-01-20 22:07:59.314701

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f07b511c58dc"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use batch_alter_table to work around SQLite's ALTER TABLE limitations
    with op.batch_alter_table("applications", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("datetime('now', 'localtime')"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("concluded_at", sa.DateTime(), nullable=True))

    with op.batch_alter_table("votes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("voted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("votes", "voted_at")
    op.drop_column("applications", "concluded_at")
    op.drop_column("applications", "created_at")
    # ### end Alembic commands ###
